package dev.aura.sundial.util;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Value;

@SuppressFBWarnings(
  value = "JLM_JSR166_UTILCONCURRENT_MONITORENTER",
  justification = "Code is generated by lombok which means I don\'t have any influence on it."
)
@Value
public class TimeCalculator {
  private static final long secondsInRealDay = TimeUnit.DAYS.toSeconds(1);
  private static final long ticksInMinecraftDay = 24000;
  private static final long ticksInMinecraftHour = ticksInMinecraftDay / 24;
  private static final long midnightOffset = (ticksInMinecraftDay * 3) / 4;

  private final double offset;

  @Getter(value = AccessLevel.PACKAGE, lazy = true)
  private final long offsetTicks = generateOffsetTicks();

  public long getWorldTime() {
    return getWorldTime(Calendar.getInstance());
  }

  public long getWorldTime(final Calendar calendar) {
    final long seconds =
        TimeUnit.HOURS.toSeconds(calendar.get(Calendar.HOUR_OF_DAY))
            + TimeUnit.MINUTES.toSeconds(calendar.get(Calendar.MINUTE))
            + calendar.get(Calendar.SECOND);

    return (((seconds * ticksInMinecraftDay) / secondsInRealDay)
            + midnightOffset
            + getOffsetTicks())
        % ticksInMinecraftDay;
  }

  private long generateOffsetTicks() {
    return (long) (offset * ticksInMinecraftHour);
  }
}
